# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{that_old_cache}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joey Robert"]
  s.date = %q{2010-04-07}
  s.description = %q{Serve old caches from memcached while you update in Rails}
  s.email = %q{joey@joeyrobert.org}
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.homepage = %q{http://github.com/joeyrobert/that_old_cache}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Serve old caches from memcached while you update in Rails}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<yajl-ruby>, [">= 0.7.5"])
      s.add_runtime_dependency(%q<activesupport>, [">= 2.3.5"])
    else
      s.add_dependency(%q<yajl-ruby>, [">= 0.7.5"])
      s.add_dependency(%q<activesupport>, [">= 2.3.5"])
    end
  else
    s.add_dependency(%q<yajl-ruby>, [">= 0.7.5"])
    s.add_dependency(%q<activesupport>, [">= 2.3.5"])
  end
end
